<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/photos/types/date_range.proto

namespace GPBMetadata\Google\Photos\Types;

class DateRange
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Type\Date::initOnce();
        $pool->internalAddGeneratedFile(
            '
‰
$google/photos/types/date_range.protogoogle.photos.types"W
	DateRange%

start_date (2.google.type.Date#
end_date (2.google.type.DateBk
com.google.photos.types.protoBDateRangeProtoPZ8google.golang.org/genproto/googleapis/photos/types;typesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

